version: '3.8'

services:
  proxy:
    build: ./
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      TARGET_IPS: "http1, http2"
      TARGET_PORTS: "80,80"
      LISTEN_PORTS: "80,8080"
      KEYWORD: "EH! VOLEVI"
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - "./proxy:/src/proxy"
    container_name: proxy

networks:
  default:
    name: ctf_network