version: '3.8'

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  proxy:
    build: ./
    hostname: proxy
    container_name: proxy
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    # ports:
    #   - 80:80
      # - 443:443
    volumes:
      - "./proxy:/proxy"

networks:
  default:
    name: ctf_network