version: '3.8'

services:
  proxy:
    build: ./
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      TARGET_IPS: "example1, example2, 192.168.1.100"
      TARGET_PORTS: "9090,9091,9092"
      LISTEN_PORTS: "8080,8081,8082"
      KEYWORD: "EXAMPLEKEYWORD"
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - "./proxy:/src/proxy"
    container_name: proxy

networks:
  default:
    name: ctf_network