version: '3.8'

services:
  proxy:
    build: ./
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "./proxy:/proxy"
    container_name: proxy

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
    container_name: db

networks:
  default:
    name: ctf_network