version: '3.8'

services:
  proxy:
    build: ./
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./proxy:/proxy"
    container_name: proxy

networks:
  default:
    name: ctf_network